package(default_visibility = ["//visibility:public"])


cc_library(
  name = "spiro",
  hdrs = [
    'bezctx.h',
    'bezctx_intf.h',
    'spiroentrypoints.h',
    'spiro.h',
    'spiro-config.h'
  ],
  srcs = [
    'bezctx.c',
    'spiro.c',
    'spiroentrypoints.c'
  ],
  copts = [
    '-Wno-unused-but-set-variable'
  ]
)
